ARG NODE_VERSION=18

FROM node:${NODE_VERSION}-bullseye

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get --no-install-recommends -y install gnupg2 ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists \
    && yarn global add pnpm

WORKDIR /workspaces/nitic-astronomy/

COPY ./ ./
RUN pnpm install --frozen-lockfile
